version: '3.8'  # Specifies the Docker Compose file format version.

services:
  spring-dockerized-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
        - .env
