spring:
  application:
    name: datadog
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: bank-account
      auto-index-creation: true


management:
  statsd:
    metrics:
      export:
        flavor: datadog
        enabled: true
  dogstatsd:
    metrics:
      export:
        enabled: true
        tags:
          env: local
          app: datadog-metrics-cards